name: Update Visualizations on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        platform: [Azure, AWS]
    name: Validate Mappings and Update Visualizations
    steps:
      - name:  Checking out master branch
        uses: actions/checkout@v2
        with:
          submodules: false
          token: ${{ secrets.SECURITY_STACK_MAPPINGS_CI_WORKFLOW }}
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd tools
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute validation script
        working-directory: ./tools
        run: |
          ./mapping_cli.py validate --mapping-dir ../mappings/${{ matrix.platform }}
      - name: Generate ATT&CK Navigator Visualization
        working-directory: ./tools
        run: |
          ./mapping_cli.py visualize --visualizer AttackNavigator --skip-validation --include-aggregate --mapping-dir ../mappings/${{ matrix.platform }}
      - name: Generate Markdown Summary Visualization
        working-directory: ./tools
        run: |
          ./mapping_cli.py visualize --visualizer MarkdownSummary --skip-validation --include-html --mapping-dir ../mappings/${{ matrix.platform }}
      - name: Prepare icons and images
        run: |
          mkdir -p docs/icons
          cp images/*.svg docs/icons
          cp images/*.png docs/icons
          cp images/PRPL-CTID-third.jpeg docs/icons
      - name: Updates docs folder with latest visualizations
        run: |
          rm -rf docs/${{ matrix.platform }}
          cp -r mappings/${{ matrix.platform }} docs/
      - name: Generate Index Page
        run: |
          echo '<meta http-equiv="refresh" content="0; URL=Azure/README.html" />' > docs/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          exclude_assets: '*.md'
